version: "3.7"
services:
    frontend:
        container_name: frontend
        restart: always
        build:
            context: client
            dockerfile: Dockerfile
        expose:
            - "80"
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "80:80"