version: "3.7"
services:
    app:
        container_name: frontend
        restart: unless-stopped
        build:
            context: ./client
        expose:
            - "80"
        ports:
            - "80:80"